nasilke/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('nutritions.urls')),
    url(r'^', include('articles.urls')),
    url(r'^', include('supositioner.urls')),
    url(r'^', include('users.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nutritions/urls.py
from django.conf.urls import url

from .views import CompanyListView, NutritionListView, NutritionCompanyListView, WheyDetailView, GainerDetailView,\
	 BcaaDetailView, CreatineDetailView, Eror404, Temp, WheyListView, GainerListView, BcaaListView, CreatineListView, PreWorkoutDetailView,\
	 BurnerDetailView

urlpatterns = [
	url(r'^odzywki/$', NutritionListView.as_view(), name='nutritions'),
	url(r'^bialka/$', WheyListView.as_view(), name='whey-list'),
	url(r'^gainery/$', GainerListView.as_view(), name='gainer-list'),
	url(r'^bcaa/$', BcaaListView.as_view(), name='bcaa-list'),
	url(r'^kreatyna/$', CreatineListView.as_view(), name='creatine-list'),

	url(r'^firmy/$', CompanyListView.as_view(), name='companies'),
	url(r'^odzywki-firmy-(?P<company_slug>[\w-]+)/$', NutritionCompanyListView.as_view(), name='company-nutritions'),
	
	url(r'^bialko-(?P<nutrition_slug>[\w-]+)/$', WheyDetailView.as_view(), name='whey'),
	url(r'^gainer-(?P<nutrition_slug>[\w-]+)/$', GainerDetailView.as_view(), name='gainer'),
	url(r'^bcaa-(?P<nutrition_slug>[\w-]+)/$', BcaaDetailView.as_view(), name='bcaa'),
	url(r'^spalacz-(?P<nutrition_slug>[\w-]+)/$', BurnerDetailView.as_view(), name='burner'),
	url(r'^przedtreningowka-(?P<nutrition_slug>[\w-]+)/$', PreWorkoutDetailView.as_view(), name='pre-workout'),
	url(r'^kreatyna-(?P<nutrition_slug>[\w-]+)/$', CreatineDetailView.as_view(), name='creatine'),
	url(r'^404/$', Eror404.as_view(), name='error404'),
	url(r'^temp/$', Temp.as_view(), name='temp'),
]

users/urls.py
from django.conf.urls import url
from .views import ConfirmAnonymUser


urlpatterns = [
	url(r'^potwierdz-email/(?P<token>[\w-]+)/$', ConfirmAnonymUser.as_view(), name='confirm-email'),
]

nutritions/models.py
from ckeditor_uploader.fields import RichTextUploadingField

from django.contrib import messages
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils.safestring import mark_safe
from solo.models import SingletonModel
# Create your models here.

from .utils import unique_slug_generator
from users.models import AnonymUser

#comapnies choices
POL  	= 'Polska'
USA 	= 'USA'
REST 	= 'Reszta Świata'

NATION_COMPANY_CHOICES = (
	('P', POL),
	('U', USA),
	('R', REST),
	)

#review choices
# Whey
RW1 = 'Rozpuszczalność'
RW2 = 'Smak'

# Pre-workout
RP1 = 'Pompa'
RP2 = 'Koncentracja'
RP3 = 'Pobudzenie'
RP4 = 'Czas działania'

# Burner
RB1 = 'Pobudzenie'
RB2 = 'Komfort psychiczny'
RB3 = 'Brak apetytu'

# GAINER


REVIEW_NUTRITION_FIELDS_CHOICES = (
		('RW1',RW1),
		('RW2',RW2),
		('RP1',RP1),
		('RP2',RP2),
		('RP3',RP3),
		('RP4',RP4),
		('RB1',RB1),
		('RB2',RB2),
		('RB3',RB3),
	)


class Company(models.Model):
	name 			= models.CharField(max_length=255, blank=False, null=False, unique=True, verbose_name='Nazwa firmy')
	site 			= models.CharField(max_length=255, blank=False, null=False, verbose_name='Adres strony www')
	description		= models.TextField(blank=False, null=False, verbose_name='Opis')
	logo 			= models.ImageField(upload_to='img/company/', blank=False, null=False, verbose_name='Logo')
	nation			= models.CharField(max_length=1, choices=NATION_COMPANY_CHOICES, default=POL, blank=False, null=False, verbose_name='Kraj')
	slug  			= models.SlugField(blank=True, verbose_name='Wygenerowany slug z nazwy')
	updated			= models.DateTimeField(auto_now=True)
	created		 	= models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = 'Firma'
		verbose_name_plural = '10. Firmy'

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.slug = unique_slug_generator(self)
		super(Company, self).save(*args, **kwargs)

	def logo_thumb(self):
		if self.logo:
			return mark_safe('<img src="{}" style="width:200px" />'.format(self.logo.url))
		else:
			return "Brak wgranego loga"

#NUTRITIONS
class Flavour(models.Model):
	name 			= models.CharField(max_length=255, blank=False, null=False, unique=True, verbose_name='Smak')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Smak suplementu'
		verbose_name_plural = '20. Smaki suplementów'


class NutritionForm(models.Model):
	name 			= models.CharField(max_length=255, blank=False, null=False, unique=True, verbose_name='Forma supla')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Forma suplementu'
		verbose_name_plural = '22. Formy suplementów'

class Nutrition(models.Model):
	name 				= models.CharField(max_length=255, blank=False, null=False, verbose_name='Nazwa')
	ceneo_id			= models.PositiveIntegerField(blank=False, null=False, unique=False, verbose_name='ID ceneo')
	company 			= models.ForeignKey(Company, verbose_name='Producent')
	photo				= models.ImageField(upload_to='img/nutrition/', blank=True, null=True, verbose_name='Zdjęcie')
	price 				= models.FloatField(blank=False, null=False, verbose_name='Cena (zł)')
	weight 				= models.PositiveSmallIntegerField(blank=False, null=False, verbose_name='Waga (g)')
	portion 			= models.PositiveSmallIntegerField(blank=False, null=False, verbose_name='Porcja (g)')
	kcal 				= models.PositiveSmallIntegerField(blank=False, null=False, verbose_name='Wartość kaloryczna w 100g (kcal)')
	form 				= models.ForeignKey(NutritionForm, blank=True, null=True, verbose_name='Forma supla')
	flavour 			= models.ManyToManyField(Flavour, verbose_name='Smak')
	description 		= RichTextUploadingField(blank=False, null=False, verbose_name='Opis')
	expert_note			= models.CharField(max_length=255, blank=True, null=True, verbose_name='Opinia experta')
	featured			= models.BooleanField(default=False, verbose_name='Rekomendacja')
	available			= models.BooleanField(default=True, verbose_name='Dostępne na rynku')
	rating				= models.FloatField(blank=True, null=True, verbose_name='Wyliczona wartość')
	rating_supositioner	= models.FloatField(blank=True, null=True, verbose_name='Wyliczona ocena suPositioner')
	portion_amount		= models.PositiveSmallIntegerField(blank=True, null=False, verbose_name='Wyl ilość porcji w opak.')
	slug  				= models.SlugField(blank=True, verbose_name='Wygenerowany slug z nazwy')
	updated				= models.DateTimeField(auto_now=True)
	created		 		= models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = 'Wszystkie suplementy'
		verbose_name_plural = '07. Wszystkie suplementy'

	def photo_thumb(self):
		if self.photo:
			return mark_safe('<img src="{}" style="width:250px;"/>'.format(self.photo.url))
		else:
			return 'Brak wgranego zdjęcia'
	photo_thumb.short_description = 'Zdjęcie'
	

	def get_all_compositions(self):
		return self.composition.all()

	def get_composition(self, name, request):
		obj = self.get_all_compositions().filter(nutrition_composition__field__name=name)

		if not obj:
			messages.warning(request, 'Brak pola {}'.format(name))
			return None

		return obj[0].nutrition_composition.value

	def save(self, *args, **kwargs):
		self.slug = unique_slug_generator(self)
		if self.portion and self.weight:
			self.portion_amount = self.weight / self.portion
		super(Nutrition, self).save(*args, **kwargs)


	def __str__(self):
		return self.name


class CompositionField(models.Model):
	name 			= models.CharField(max_length=255, blank=False, null=False, unique=True, verbose_name='Nazwa składnika')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Składnik'
		verbose_name_plural = '21. Składniki'

class NutritionComposition(models.Model):
	field 					= models.ForeignKey(CompositionField, blank=False, null=True, verbose_name='Nazwa składnika')
	value 					= models.FloatField(blank=False, null=False, validators=[MinValueValidator(1), MaxValueValidator(100)], verbose_name='Wartość na 100g (g)')

	def __str__(self):
		return str(self.field) + ': ' + str(self.value) + 'g'

	class Meta:
		verbose_name = 'Składnik suplemnetu'
		verbose_name_plural = '22. Składniki suplementów'


class Composition(models.Model):
	nutrition 				= models.ForeignKey(Nutrition, blank=False, null=True, related_name='composition', verbose_name='Suplement')
	nutrition_composition 	= models.ForeignKey(NutritionComposition, blank=False, null=True, verbose_name='Skład')

	def __str__(self):
		return str(self.nutrition) + " : " +  str(self.nutrition_composition)

	class Meta:
		verbose_name = 'Skład suplementu'
		verbose_name_plural = '24. Składy suplementów'


class Whey(Nutrition):

	class Meta:
		verbose_name = 'Białko'
		verbose_name_plural = '01. Białka'

	def __str__(self):
		return self.nutrition_ptr.name

	def calculate_supoistioner_rating(self, request):
		return 10


class Gainer(Nutrition):

	class Meta:
		verbose_name = 'Gainer'
		verbose_name_plural = '02. Gainery'

	def __str__(self):
		return self.nutrition_ptr.name


class Bcaa(Nutrition):

	class Meta:
		verbose_name = 'Bcaa'
		verbose_name_plural = '03. Bcaa'

	def calculate_supoistioner_rating(self, request):
		lleucine 	= self.get_composition('L-leucine', request)
		lisoleucine = self.get_composition('L-isoleucine', request)
		lvaline 	= self.get_composition('L-valine', request)

		if None in (lleucine, lisoleucine, lvaline):
			pass
		else:
			nutrition = self.nutrition_ptr
			amino = lleucine + lisoleucine + lvaline
			amino_in_portion = (((nutrition.portion*(amino))/100))
			price_per_portion = (nutrition.weight/nutrition.portion)/nutrition.price
			lleucine_in_portion = (nutrition.portion*lleucine/100)
			company = 7
			return((nutrition.portion_amount*2)+(amino_in_portion*6)+(price_per_portion*4)+(lleucine_in_portion*8)+(company*1))/(2+6+4+8+1)
			# return ((nutrition.price * 100 / nutrition.weight) / ( (amino / nutrition.weight)*0.4 + (lleucine / amino)* 0.6 ))

	def __str__(self):
		return self.nutrition_ptr.name


M = "Monohydrat kreatyny"
J = "Jabłczan kreatyny"
CREATINE_FORM_CHOICES = (
		('M', M),
		('J', J),
	)

class Creatine(Nutrition):
	class Meta:
		verbose_name = 'Kreatyna'
		verbose_name_plural = '04. Kreatyny'

	creatine_form  	= models.CharField(max_length=1, choices=CREATINE_FORM_CHOICES, default=M, blank=True, null=False, verbose_name='Forma kreatyny')

	def __str__(self):
		return self.nutrition_ptr.name



class PreWorkout(Nutrition):

	class Meta:
		verbose_name = 'PreWorkout'
		verbose_name_plural = '05. PreWorkout'

	def __str__(self):
		return self.nutrition_ptr.name

	def calculate_supoistioner_rating(self, request):
		return 10

class Burner(Nutrition):

	class Meta:
		verbose_name = 'Burner'
		verbose_name_plural = '06. Burner'

	def __str__(self):
		return self.nutrition_ptr.name

	def calculate_supoistioner_rating(self, request):
		return 10
# REVIEWS

class CustomNutritionReviewManager(models.Manager):
	def get_queryset(self):
		return super(CustomNutritionReviewManager, self).get_queryset().filter(Q(approved=True) & Q(author__confirmed=True) & Q(author__banned=False))


class NutritionReview(models.Model):
	# nutrition_type 			= models.CharField(max_length=1, choices=REVIEW_NUTRITION_CHOICES, default=R1, blank=False, null=False)
	nutrition 				= models.ForeignKey(Nutrition, blank=False, null=True)
	author	 				= models.ForeignKey(AnonymUser, blank=False, null=True)
	review 					= models.CharField(max_length=255, blank=False, null=False)
	
	approved 				= models.BooleanField(default=False)
	created 				= models.DateTimeField(auto_now_add=True)

	objects 				= models.Manager()
	cobjects 				= CustomNutritionReviewManager()


	class Meta:
		verbose_name = 'Recenzja'
		verbose_name_plural = 'Recenzje'

	def __str__(self):
		return self.nutrition.name + ' (' + self.author.email + ')'


class ReviewField(models.Model):

nutritions/forms.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator, MinLengthValidator
from django.contrib import messages

from users.models import AnonymUser
from .models import NutritionReview, ReviewField

class NutritionBaseReviewForm(forms.Form):
	nick			= forms.CharField(max_length=32, validators=[MinLengthValidator(2)])
	email			= forms.EmailField(required=True)
	review 			= forms.CharField(max_length=255, widget=forms.Textarea, required=True)

	def save_base(self):
		if self.is_valid():
			nick 	= self.cleaned_data['nick']
			email 	= self.cleaned_data['email']
			review  = self.cleaned_data['review']

			author = AnonymUser.create_anonym_user(email, nick)

			return author, review
		print('valid error')

class WheyReviewForm(NutritionBaseReviewForm):
	solubility		= forms.IntegerField(label='Rozpuszczalność' , required=True, validators=[MinValueValidator(1), MaxValueValidator(5)], widget=forms.HiddenInput())
	taste			= forms.IntegerField(label='Smak', required=True, validators=[MinValueValidator(1), MaxValueValidator(5)], widget=forms.HiddenInput())

	def get_review_fields(self):
		return ['solubility', 'taste', ]

	def review_save(self, nutrition):
		if self.is_valid():
			solubility 	= self.cleaned_data['solubility']
			taste		= self.cleaned_data['taste']
		
			author, review = self.save_base()

			nutirition_review = NutritionReview(nutrition=nutrition, author=author, review=review)
			nutirition_review.save()

			rw1 = ReviewField(field='RW1', value=int(solubility), review=nutirition_review)
			rw1.save()

			rw2 = ReviewField(field='RW2', value=int(taste), review=nutirition_review)
			rw2.save()

			return author


class PreWorkoutReviewForm(NutritionBaseReviewForm):
	pump			= forms.IntegerField(required=True, validators=[MinValueValidator(1), MaxValueValidator(5)], widget=forms.HiddenInput())
	concentration	= forms.IntegerField(required=True, validators=[MinValueValidator(1), MaxValueValidator(5)], widget=forms.HiddenInput())
	stimulation		= forms.IntegerField(required=True, validators=[MinValueValidator(1), MaxValueValidator(5)], widget=forms.HiddenInput())
	worktime 		= forms.IntegerField(required=True, validators=[MinValueValidator(1), MaxValueValidator(5)], widget=forms.HiddenInput())

	pump.label			= 'Pompa'
	concentration.label = 'Koncentracja'
	stimulation.label 	= 'Pobudzenie'
	worktime.lebel 		= 'Czas działania'

	def get_review_fields(self):
		return ['pump', 'concentration', 'stimulation', 'worktime', ]

	def review_save(self, nutrition):
		if self.is_valid():
			pump 			= self.cleaned_data['pump']
			concentration	= self.cleaned_data['concentration']
			stimulation		= self.cleaned_data['stimulation']
			worktime		= self.cleaned_data['worktime']
		
			author, review = self.save_base()

			nutirition_review = NutritionReview(nutrition=nutrition, author=author, review=review)
			nutirition_review.save()

			rp1 = ReviewField(field='RP1', value=int(pump), review=nutirition_review)
			rp1.save()

			rp2 = ReviewField(field='RP2', value=int(concentration), review=nutirition_review)
			rp2.save()

			rp3 = ReviewField(field='RP3', value=int(stimulation), review=nutirition_review)
			rp3.save()

			rp4 = ReviewField(field='RP4', value=int(worktime), review=nutirition_review)
			rp4.save()

			return author

class BurnerReviewForm(NutritionBaseReviewForm):
	stimulation			= forms.IntegerField(label='Pobudzenie' , required=True, validators=[MinValueValidator(1), MaxValueValidator(5)], widget=forms.HiddenInput())
	phisical_comfort	= forms.IntegerField(label='Komfort psychiczny', required=True, validators=[MinValueValidator(1), MaxValueValidator(5)], widget=forms.HiddenInput())
	no_appetite			= forms.IntegerField(label='Brak apetytu', required=True, validators=[MinValueValidator(1), MaxValueValidator(5)], widget=forms.HiddenInput())

	def get_review_fields(self):
		return ['stimulation', 'phisical_comfort', 'no_appetite', ]

	def review_save(self, nutrition):
		if self.is_valid():

			stimulation 		= self.cleaned_data['stimulation']
			phisical_comfort 	= self.cleaned_data['phisical_comfort']
			no_appetite 		= self.cleaned_data['no_appetite']
		
			author, review = self.save_base()

			nutirition_review = NutritionReview(nutrition=nutrition, author=author, review=review)
			nutirition_review.save()

			rw1 = ReviewField(field='RB1', value=int(stimulation), review=nutirition_review)
			rw1.save()

			rw2 = ReviewField(field='RB2', value=int(phisical_comfort), review=nutirition_review)
			rw2.save()

			rw3 = ReviewField(field='RB2', value=int(no_appetite), review=nutirition_review)
			rw3.save()

			return author

templates/nutritions/company_list.html
{% extends '../index.html' %}

{% block header %}
{% endblock %}

{% block main %}
<section class="my-5">
	<div class="album text-muted content-wrapper">
	      <div class="container">
	      	<h3 class="text-center">Producenci</h3>
	      	{% for object in object_list %}
		      	{% if forloop.counter.first or forloop.counter0|divisibleby:3 %}
					 <div class="row">
				{% endif %}
				  <div class="col-md-4">
				    <div class="card list-card text-center pt-3" style="height: 200px;">
					      <a href="{% url 'company-nutritions' company_slug=object.slug %}">
					      	{% if object.logo %}
					      		<img class="card-img-top" style="width:200px; max-height: 110px;" src="{{ object.logo.url }}" alt="Card image cap">
					      	{% endif %}
					      </a>
					      <div class="card-body d-flex flex-row align-items-end justify-content-center" style="height: 100%;">
					       		<div class="h3 card-title">
							       	<a href="{% url 'company-nutritions' company_slug=object.slug %}">
							       		{{ object.name }}
							        </a>
					        	</div>
					        {% if object.nation == 'P' %}
					        	<div class="card-text">Polska firma</div>
					        {% endif %}
					      </div>
					    </div>
					  </div>
				{% if forloop.counter|divisibleby:3 or forloop.last %}
					 </div>
				{% endif %}
			{% endfor %}
		</div>
	</div>
</section>
{% endblock %}

templates/nutritions/nutrition_company_list.html
{% extends '../base.html' %}
{% load static %}

{% block main_header %}
	<div class="row">
		<div class="col-sm-5">
			<p><img src="{{ company_logo }}" style="width: 400px; height: 400px;"></p>
			<h5 class="text-center">{{ company_name }}</h5>
			<h5 class="text-center"><a href="{{ company_site }}" target="_blank">Przejdź do strony producenta</a></h5>
		</div>
		<div class="col-sm-6 mt-5">
			<h4>{{ company_description }}</h4>
		</div>
	</div>
{% endblock %}
{% block photo %}{% endblock %}
{% block header %}
	{{ block.super }}
{% endblock %}

{% block main %}
<div class="album text-muted content-wrapper">
      <div class="container">
      	{% for object in object_list %}
	      	{% if forloop.counter == 1 or forloop.counter|divisibleby:4 %}
				 <div class="row">
			{% endif %}
				  <div class="col-sm-4">
				    <div class="card">
				      <a href="{% url 'whey' nutrition_slug=object.slug %}">
				      	<img class="card-img-top" style="width:200px; height:200px;" src="{{ object.photo.url }}" alt="Card image cap">
				      </a>
				      <div class="card-body">
				       	<a href="{% url 'whey' nutrition_slug=object.slug %}">
				       	 <h4 class="card-title">{{ object.name }}</h4>
				        </a>
				        <p class="card-text">{{ object }}</p>
				      </div>
				    </div>
				  </div>
			{% if forloop.counter|divisibleby:3 %}
				 </div>
			{% endif %}
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/nutritions/nutrition_detail.html
{% extends '../index.html' %}
{% load static %}
{% load nutrition_tags %}
{% load utils %}

{% block style %}
    <link href="{% static 'form-outline.css' %}" rel="stylesheet">
{% endblock %}

{% block header %}
{% endblock %}

{% block main %}
<div class="album text-muted content-wrapper">
      <div class="container">
		<div class="row">
			  <div class="col-md-4 text-center mb-5">
			  	{% if object.photo %}
			    	<img src="{{ object.photo.url }}" class="{% get_class object %}-left-bar" style="width:300px; height: 300px;">
			    {% endif %}

			    <h2 class="">
				    {% for star in rank|stars %}
				    	{% if star  == 'f' %}
				  			<i class="fa fa-star" aria-hidden="true"></i>
				    	{% elif star == 'h' %}
				    		<i class="fa fa-star-half-o" aria-hidden="true"></i>
				    	{% elif star == 'e' %}
				    		<i class="fa fa-star-o" aria-hidden="true"></i>
				    	{% endif %}
				    {% endfor %}
			     </h2>
			   	<h2 class="nutrition-price mt-5">{{ object.price|floatformat:2 }} zł</h2>
			   	<div class="btn btn-danger" role='button'>ceneo</div>
			  </div>
			  <div class="col-md-7 ml-3">
			    <h2>{{ object.name }}</h2>
			    <h4><a href="{% url 'company-nutritions' company_slug=object.company.slug %}">{{ object.company.name }}</a></h4>
			    <p>{% autoescape off %}{{ object.description|safe }}{% endautoescape %}</p>
				<div class="row mt-5">
					<div class="col-sm-4">Waga </div>
					<div class="col-sm-4">{{ object.weight }}g</div>
				</div>
				<div class="nutrition-composition mt-4">
				    <div class="row">
				    	<div class="col-sm-4"><strong>Nazwa</strong></div>
				    	<div class="col-sm-8 text-right"><strong>wartość w 100g</strong></div>
				    </div>
				    {% if object.kcal %}
					   	<div class="row">
					    	<div class="col-sm-4">Kaloryczność </div>
					    	<div class="col-sm-8 text-right">{{ object.kcal }} kcal</div>
					    </div>
				   	{% endif %}
				   	<div class="row">
				    	<div class="col-sm-4">Dostępne smaki </div>
				    	<div class="col-sm-8 text-right">{% for flavour in object.flavour.all %}{{ flavour.name }} {% endfor %}</div>
				    </div>
				    {% for composition in compositions %}
					    <div class="row">
					    	<div class="col-sm-4">{{ composition.field.name }} </div>
					    	<div class="col-sm-8 text-right">{{ composition.value }}g</div>
					    </div>
				    {% endfor %}
				 </div>
			 </div>
		 </div>
	</div>
	{% include 'nutritions/nutrition_reviews.html' %}
</div>
{% endblock %}

{% block script %}
<script>
var $ranks = $('#rank-stars').find('div.star-rating')

var SetRatingStar = function() {
  return $ranks.children().each(function() {
    if (parseInt($(this).siblings('input.rating-value').val()) >= parseInt($(this).data('rating'))) {
      return $(this).removeClass('fa-star-o').addClass('fa-star');
    } else {
      return $(this).removeClass('fa-star').addClass('fa-star-o');
    }
  });
};

$ranks.children().on('click', function() {
	$(this).siblings('input.rating-value').val($(this).data('rating'));
	return SetRatingStar();
});

SetRatingStar();
</script>
{% endblock %}

templates/nutritions/nutrition_reviews.html
{% load forms_attrs %}
{% load utils %}

<div class="container comments-wrapper">
	<div class="row comments-header-main comments-header-line">
		<div>Recenzje suplementu</div>
	</div>
	{% for review in reviews %}
		<div class="row">
			<div class="col-md-12 p-3">
				<div class="comments-avatar-wrapper">
					<div class="comments-avatar"></div>
				</div>
				<div class="ml-3">
					<div class="row">
						<div class="col-md-7">
							<div><strong>{{ review.author.nick }}</strong><small class="text-muted"> {{ review.created|age }}</small></div>
							<div>{{ review.review }}</div>
						</div>
						<div class="col-md-5">
							{% for field in review.review_fields.all %}
							<div>
								<div class="comments-rank-fields">{{ field.get_field_display }}:</div>
								<div class="text-right">
									{% for rate in field.value|range %}
										<i class="fa fa-star" aria-hidden="true"></i>
									{% endfor %}
									{% for rate in field.value|range_rest %}
										<i class="fa fa-star-o" aria-hidden="true"></i>
									{% endfor %}
								</div>
							</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
	{% endfor %}
	<div class="row comments-header-new comments-header-line">
		<div>Dodaj nową recenzję</div>	
	</div>
	<div class="row">
		<div class="col-md-8 mx-auto comments-new-wrapper">
			{% if form %}
				<form method="POST">
					{% csrf_token %}
					<div class="row">
						<div class="col-md-6 mt-1">
							{{ form.review|addatr:"class:form-control, rows:6, placeholder:Jak oceniasz suplement?" }}
						</div>
						<div class="col-lg-5 mt-2" id="rank-stars">
							{% for field in rank_form %}
								<div class="comments-rank-fields">{{ field.label }}</div>
								<div class="star-rating text-right"> 
									<span class="fa fa-star-o" data-rating="1"></span>
									<span class="fa fa-star-o" data-rating="2"></span>
									<span class="fa fa-star-o" data-rating="3"></span>
									<span class="fa fa-star-o" data-rating="4"></span>
									<span class="fa fa-star-o" data-rating="5"></span>
									{{ field|addatr:"class:rating-value" }}
	    						</div>
    						{% endfor %}
    					</div>
    				</div>
					<div class="row">
						<div class="col-md-6">
							<div class="row">
								<div class="col-md-12">
									{{ form.nick|addatr:"class:form-control, placeholder:Podaj nick" }}
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">
									{{ form.email|addatr:"class:form-control, placeholder:Podaj swój email" }}
								</div>
							</div>
						</div>
						<div class="col-auto m-auto">
							<button type="submit" class="btn btn-outline-primary">Opublikuj recenzję<i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
						</div>
					</div>
				</form>
			{% endif %}
		</div>
	</div>
</div>